### ISSUE TITLE
Using kafka as event bus and cassandra as event store

### ISSUE THREAD

**Issue by fortm** [holisticon/axon-kafka#1]
Hi

Can we use axon-kafka to replace rabbitmq with kafka as eventbus for latest Axon version 3.*
I am trying to use axonframework in existing project that has kafka and cassandra. With that respect, wanted to have kafka as eventbus instead of rabbitmq and cassandra as eventstore instead of mongodb.

Thanks

**Comment by jangalinski** [comment]
Yes, the goal of this project is to allwo using kafka instead of rabbit with axon. But its far from finished and unrelased ... (and currently not our highest prio)
